# This workflow will build a Java project with Gradle initially
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Simple Pipe

on:
  push:
    branches: [ debug ]
  pull_request:
    branches: [ debug ]
  workflow_dispatch:
    inputs:
      myValues:
        description: 'Input Values'

jobs:

  info:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print warning message
      run: |
        echo "::warning::This version is for debugging only."
    - name: Dump context for runner
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run:
        echo "::debug::Runner context is above."
      
      
